version: "3.8"
services:
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - data:/data/db
    image: mongo
    networks:
      - shopping
      
  backend:
    ports:
      - 80:80
    volumes:
      - logs:/logs
      - node_modules:/node_modules
    networks:
      - shopping
    image: smokingdice/shoppinglist-backend
       
  frontend:
    networks:
      - shopping
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/src
    image: smokingdice/shoppinglist-frontend

networks:
  goals:

volumes:
  data:
  logs:
  node_modules:
